---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mattcosgrove/ansible-1804-sshpass
    tag: latest

inputs:
  - name: ubuntu-ansible-playbook
  - name: vm-ip-address
  - name: concourse-tasks

params:
  VM_USERNAME: ((ubuntu_vm_username))
  VM_PASSWORD: ((ubuntu_vm_password))
  GIT_CONFIG_USERNAME: matthewcosgrove
  GIT_CONFIG_EMAIL: mc.matthew.cosgrove@gmail.com

run:
  path: ./concourse-tasks/ci/tasks/ubuntu-day-one/run-ansible-playbook/task.sh

