---
- name: Provision Tools VM
  hosts: all

  collections:
  - matthewcosgrove.tools_vm
  tasks:
  - name: "Include ubuntu_user"
    include_role:
      name: "ubuntu_user"
    vars:
      ansible_become: yes
  - name: "Include vim"
    include_role:
      name: "vim"
    vars:
      ansible_become: yes
  - name: Recursively change ownership of a directory
    file:
      path: /home/ubuntu/.vim
      state: directory
      recurse: yes
      owner: ubuntu
      group: ubuntu
    become: true
  - name: "Include vim_plugins"
    include_role:
      name: "vim_plugins"
    vars:
      ansible_become: yes
  - name: "Include bucc_tools"
    include_role:
      name: "bucc_tools"
    vars:
      ansible_become: yes
  - name: "Include geerlingguy.packer role"
    include_role:
      name: "geerlingguy.packer"
    vars:
      ansible_become: yes
      packer_version: "1.6.4"
  - name: clone lab-ops bucc helper for vcenter
    git:
      repo: "https://github.com/matthewcosgrove/lab-ops.git"
      dest: "/home/ubuntu/lab-ops"
      version: "master"
      accept_hostkey: yes
  - name: clone tools vm provisioning scripts
    git:
      repo: "https://github.com/matthewcosgrove/tools-vm-scripts.git"
      dest: "/home/ubuntu/tools-vm-scripts"
      version: "master"
      accept_hostkey: yes
  - name: Create user specific .gitconfig
    template:
      src: gitconfig.j2
      dest: /home/ubuntu/.gitconfig
  - name: Install minio cli
    script: scripts/install_minio_cli.sh
  - name: Create symbolic links for dotfiles
    file:
      src: "/home/ubuntu/tools-vm-scripts/dotfiles/{{ item }}"
      dest: "/home/ubuntu/{{ item }}"
      state: link
    loop:
     - .vimrc
     - .bash_aliases
     - .functions
  - name: Create .env_bucc for GOVC_, VCENTER_ and BUCC_ env vars
    template:
      src: env_bucc.j2
      dest: /home/ubuntu/.env_bucc
      force: no # Important as these env vars are configured by the user
  - name: Insert/Update .profile
    blockinfile:
      path: /home/ubuntu/.profile
      insertbefore: BOF
      marker: "# {mark} ANSIBLE MANAGED BLOCK FOR BUCC HELPERS"
      block: |
        export BUCC_WRAPPER_ROOT_DIR="/home/ubuntu/lab-ops"
        state_repo_root_dir="/home/ubuntu/lab-ops-state"
        export BBL_STATE_DIR="${state_repo_root_dir}/state" # BBL_STATE_DIR is the convention use by BUCC https://github.com/starkandwayne/bucc/blob/2af7a2b47a151007b4db089f2349aa58bce8d1fc/bin/bucc#L8  
        export PATH=/home/ubuntu/lab-ops/bin:/home/ubuntu/lab-ops/src/bucc/bin:/home/ubuntu/.local/bin:"${PATH}"
        if [ -f /home/ubuntu/.functions ]; then
            . /home/ubuntu/.functions
            mgmt # bin/bucc_env sourcing
        fi
        if [ -f /home/ubuntu/.env_bucc ]; then
            . /home/ubuntu/.env_bucc
        fi
  - name: Make directory for /home/ubuntu/lab-ops-state/state
    file:
      path: /home/ubuntu/lab-ops-state/state
      state: directory
  - name: Ensure /home/ubuntu/lab-ops-state/.gitignore exists and prevents director-vars-*.yml being commited
    lineinfile:
      path: /home/ubuntu/lab-ops-state/.gitignore
      line: director-vars-*.yml
      create: yes
