---
- name: Provision Tools VM
  hosts: all

  collections:
  - matthewcosgrove.tools_vm
  tasks:
  - name: "Include ubuntu_user"
    include_role:
      name: "ubuntu_user"
    vars:
      ansible_become: yes
