#!/bin/bash
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
: "${FINAL_PIPELINE_YAML:? FINAL_PIPELINE_YAML must be set }"

spruce merge "${SCRIPT_DIR}"/pipeline/*.yml > "${FINAL_PIPELINE_YAML}"

